In [1]:
import numpy as np

# Define matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Problem 1: Matrix multiplication by hand (Mathematical explanation in Markdown)
# Calculation:
# C[0,0] = (-1*0) + (2*0) + (3*2) = 6
# C[0,1] = (-1*2) + (2*2) + (3*9) = 27
# C[0,2] = (-1*1) + (2*-8) + (3*-1) = -20
# C[1,0] = (4*0) + (-5*0) + (6*2) = 12
# C[1,1] = (4*2) + (-5*2) + (6*9) = 40
# C[1,2] = (4*1) + (-5*-8) + (6*-1) = 38
# C[2,0] = (7*0) + (8*0) + (-9*2) = -18
# C[2,1] = (7*2) + (8*2) + (-9*9) = -47
# C[2,2] = (7*1) + (8*-8) + (-9*-1) = -47

# Problem 2: Using NumPy functions
result_matmul = np.matmul(a_ndarray, b_ndarray)
result_dot = np.dot(a_ndarray, b_ndarray)
result_at = a_ndarray @ b_ndarray
print("Result using np.matmul:\n", result_matmul)
print("Result using np.dot:\n", result_dot)
print("Result using @ operator:\n", result_at)

# Problem 3: Implementing a single element calculation from scratch
def calculate_element(A, B, row, col):
    return sum(A[row, k] * B[k, col] for k in range(A.shape[1]))

print("Element at (0,0):", calculate_element(a_ndarray, b_ndarray, 0, 0))

# Problem 4: Implementing full matrix multiplication from scratch
def matrix_multiply(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Number of columns in A must match number of rows in B")
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            result[i, j] = calculate_element(A, B, i, j)
    return result

print("Matrix product computed from scratch:\n", matrix_multiply(a_ndarray, b_ndarray))

# Problem 5: Handling invalid input matrices
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def safe_matrix_multiply(A, B):
    if A.shape[1] != B.shape[0]:
        print("Matrix multiplication is not defined for these dimensions.")
        return None
    return matrix_multiply(A, B)

print("Attempting invalid multiplication:", safe_matrix_multiply(d_ndarray, e_ndarray))

# Problem 6: Transposing and multiplying
transposed_result = np.matmul(a_ndarray.T, b_ndarray)
print("Matrix product after transposing A:\n", transposed_result)

Result using np.matmul:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Result using np.dot:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Result using @ operator:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Element at (0,0): 6
Matrix product computed from scratch:
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
Matrix multiplication is not defined for these dimensions.
Attempting invalid multiplication: None
Matrix product after transposing A:
 [[ 14  69 -40]
 [ 16  66  34]
 [-18 -63 -36]]
